// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/seWy-bit/GO-and-eat/internal/order/domain"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// MockOrderCreator is an autogenerated mock type for the OrderCreator type
type MockOrderCreator struct {
	mock.Mock
}

type MockOrderCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderCreator) EXPECT() *MockOrderCreator_Expecter {
	return &MockOrderCreator_Expecter{mock: &_m.Mock}
}

// CreateOrderWithTx provides a mock function with given fields: ctx, tx, order
func (_m *MockOrderCreator) CreateOrderWithTx(ctx context.Context, tx pgx.Tx, order domain.Order) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrderWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, domain.Order) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderCreator_CreateOrderWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrderWithTx'
type MockOrderCreator_CreateOrderWithTx_Call struct {
	*mock.Call
}

// CreateOrderWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - order domain.Order
func (_e *MockOrderCreator_Expecter) CreateOrderWithTx(ctx interface{}, tx interface{}, order interface{}) *MockOrderCreator_CreateOrderWithTx_Call {
	return &MockOrderCreator_CreateOrderWithTx_Call{Call: _e.mock.On("CreateOrderWithTx", ctx, tx, order)}
}

func (_c *MockOrderCreator_CreateOrderWithTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, order domain.Order)) *MockOrderCreator_CreateOrderWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(domain.Order))
	})
	return _c
}

func (_c *MockOrderCreator_CreateOrderWithTx_Call) Return(_a0 error) *MockOrderCreator_CreateOrderWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderCreator_CreateOrderWithTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, domain.Order) error) *MockOrderCreator_CreateOrderWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderCreator creates a new instance of MockOrderCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderCreator {
	mock := &MockOrderCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
