// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionManager is an autogenerated mock type for the TransactionManager type
type MockTransactionManager struct {
	mock.Mock
}

type MockTransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionManager) EXPECT() *MockTransactionManager_Expecter {
	return &MockTransactionManager_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockTransactionManager) Begin(ctx context.Context) (pgx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionManager_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockTransactionManager_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionManager_Expecter) Begin(ctx interface{}) *MockTransactionManager_Begin_Call {
	return &MockTransactionManager_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockTransactionManager_Begin_Call) Run(run func(ctx context.Context)) *MockTransactionManager_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTransactionManager_Begin_Call) Return(_a0 pgx.Tx, _a1 error) *MockTransactionManager_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionManager_Begin_Call) RunAndReturn(run func(context.Context) (pgx.Tx, error)) *MockTransactionManager_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: tx
func (_m *MockTransactionManager) Commit(tx pgx.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pgx.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionManager_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockTransactionManager_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - tx pgx.Tx
func (_e *MockTransactionManager_Expecter) Commit(tx interface{}) *MockTransactionManager_Commit_Call {
	return &MockTransactionManager_Commit_Call{Call: _e.mock.On("Commit", tx)}
}

func (_c *MockTransactionManager_Commit_Call) Run(run func(tx pgx.Tx)) *MockTransactionManager_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pgx.Tx))
	})
	return _c
}

func (_c *MockTransactionManager_Commit_Call) Return(_a0 error) *MockTransactionManager_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionManager_Commit_Call) RunAndReturn(run func(pgx.Tx) error) *MockTransactionManager_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: tx
func (_m *MockTransactionManager) Rollback(tx pgx.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pgx.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionManager_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockTransactionManager_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - tx pgx.Tx
func (_e *MockTransactionManager_Expecter) Rollback(tx interface{}) *MockTransactionManager_Rollback_Call {
	return &MockTransactionManager_Rollback_Call{Call: _e.mock.On("Rollback", tx)}
}

func (_c *MockTransactionManager_Rollback_Call) Run(run func(tx pgx.Tx)) *MockTransactionManager_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pgx.Tx))
	})
	return _c
}

func (_c *MockTransactionManager_Rollback_Call) Return(_a0 error) *MockTransactionManager_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionManager_Rollback_Call) RunAndReturn(run func(pgx.Tx) error) *MockTransactionManager_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionManager creates a new instance of MockTransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionManager {
	mock := &MockTransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
