// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/seWy-bit/GO-and-eat/internal/restaurant/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockMenuGetter is an autogenerated mock type for the MenuGetter type
type MockMenuGetter struct {
	mock.Mock
}

type MockMenuGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMenuGetter) EXPECT() *MockMenuGetter_Expecter {
	return &MockMenuGetter_Expecter{mock: &_m.Mock}
}

// GetMenu provides a mock function with given fields: restaurantID
func (_m *MockMenuGetter) GetMenu(restaurantID string) ([]domain.MenuItem, error) {
	ret := _m.Called(restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for GetMenu")
	}

	var r0 []domain.MenuItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.MenuItem, error)); ok {
		return rf(restaurantID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.MenuItem); ok {
		r0 = rf(restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MenuItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMenuGetter_GetMenu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMenu'
type MockMenuGetter_GetMenu_Call struct {
	*mock.Call
}

// GetMenu is a helper method to define mock.On call
//   - restaurantID string
func (_e *MockMenuGetter_Expecter) GetMenu(restaurantID interface{}) *MockMenuGetter_GetMenu_Call {
	return &MockMenuGetter_GetMenu_Call{Call: _e.mock.On("GetMenu", restaurantID)}
}

func (_c *MockMenuGetter_GetMenu_Call) Run(run func(restaurantID string)) *MockMenuGetter_GetMenu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMenuGetter_GetMenu_Call) Return(_a0 []domain.MenuItem, _a1 error) *MockMenuGetter_GetMenu_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMenuGetter_GetMenu_Call) RunAndReturn(run func(string) ([]domain.MenuItem, error)) *MockMenuGetter_GetMenu_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMenuGetter creates a new instance of MockMenuGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMenuGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMenuGetter {
	mock := &MockMenuGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
