// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/seWy-bit/GO-and-eat/internal/order/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUserOrdersGetter is an autogenerated mock type for the UserOrdersGetter type
type MockUserOrdersGetter struct {
	mock.Mock
}

type MockUserOrdersGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserOrdersGetter) EXPECT() *MockUserOrdersGetter_Expecter {
	return &MockUserOrdersGetter_Expecter{mock: &_m.Mock}
}

// GetOrdersByUser provides a mock function with given fields: ctx, userID
func (_m *MockUserOrdersGetter) GetOrdersByUser(ctx context.Context, userID string) ([]domain.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUser")
	}

	var r0 []domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserOrdersGetter_GetOrdersByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersByUser'
type MockUserOrdersGetter_GetOrdersByUser_Call struct {
	*mock.Call
}

// GetOrdersByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserOrdersGetter_Expecter) GetOrdersByUser(ctx interface{}, userID interface{}) *MockUserOrdersGetter_GetOrdersByUser_Call {
	return &MockUserOrdersGetter_GetOrdersByUser_Call{Call: _e.mock.On("GetOrdersByUser", ctx, userID)}
}

func (_c *MockUserOrdersGetter_GetOrdersByUser_Call) Run(run func(ctx context.Context, userID string)) *MockUserOrdersGetter_GetOrdersByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserOrdersGetter_GetOrdersByUser_Call) Return(_a0 []domain.Order, _a1 error) *MockUserOrdersGetter_GetOrdersByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserOrdersGetter_GetOrdersByUser_Call) RunAndReturn(run func(context.Context, string) ([]domain.Order, error)) *MockUserOrdersGetter_GetOrdersByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserOrdersGetter creates a new instance of MockUserOrdersGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserOrdersGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserOrdersGetter {
	mock := &MockUserOrdersGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
