// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockStockChecker is an autogenerated mock type for the StockChecker type
type MockStockChecker struct {
	mock.Mock
}

type MockStockChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockChecker) EXPECT() *MockStockChecker_Expecter {
	return &MockStockChecker_Expecter{mock: &_m.Mock}
}

// CheckAvailabilityWithTx provides a mock function with given fields: ctx, tx, restaurantID, items
func (_m *MockStockChecker) CheckAvailabilityWithTx(ctx context.Context, tx pgx.Tx, restaurantID string, items []struct {
	ID       string
	Quantity int
}) (bool, error) {
	ret := _m.Called(ctx, tx, restaurantID, items)

	if len(ret) == 0 {
		panic("no return value specified for CheckAvailabilityWithTx")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string, []struct {
		ID       string
		Quantity int
	}) (bool, error)); ok {
		return rf(ctx, tx, restaurantID, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string, []struct {
		ID       string
		Quantity int
	}) bool); ok {
		r0 = rf(ctx, tx, restaurantID, items)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string, []struct {
		ID       string
		Quantity int
	}) error); ok {
		r1 = rf(ctx, tx, restaurantID, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStockChecker_CheckAvailabilityWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAvailabilityWithTx'
type MockStockChecker_CheckAvailabilityWithTx_Call struct {
	*mock.Call
}

// CheckAvailabilityWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - restaurantID string
//   - items []struct{ID string;Quantity int}
func (_e *MockStockChecker_Expecter) CheckAvailabilityWithTx(ctx interface{}, tx interface{}, restaurantID interface{}, items interface{}) *MockStockChecker_CheckAvailabilityWithTx_Call {
	return &MockStockChecker_CheckAvailabilityWithTx_Call{Call: _e.mock.On("CheckAvailabilityWithTx", ctx, tx, restaurantID, items)}
}

func (_c *MockStockChecker_CheckAvailabilityWithTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, restaurantID string, items []struct {
	ID       string
	Quantity int
})) *MockStockChecker_CheckAvailabilityWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(string), args[3].([]struct {
			ID       string
			Quantity int
		}))
	})
	return _c
}

func (_c *MockStockChecker_CheckAvailabilityWithTx_Call) Return(_a0 bool, _a1 error) *MockStockChecker_CheckAvailabilityWithTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStockChecker_CheckAvailabilityWithTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, string, []struct {
	ID       string
	Quantity int
}) (bool, error)) *MockStockChecker_CheckAvailabilityWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockChecker creates a new instance of MockStockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockChecker {
	mock := &MockStockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
