// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/seWy-bit/GO-and-eat/internal/order/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderStatusUpdater is an autogenerated mock type for the OrderStatusUpdater type
type MockOrderStatusUpdater struct {
	mock.Mock
}

type MockOrderStatusUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderStatusUpdater) EXPECT() *MockOrderStatusUpdater_Expecter {
	return &MockOrderStatusUpdater_Expecter{mock: &_m.Mock}
}

// UpdateOrderStatus provides a mock function with given fields: ctx, id, newStatus
func (_m *MockOrderStatusUpdater) UpdateOrderStatus(ctx context.Context, id string, newStatus domain.OrderStatus) error {
	ret := _m.Called(ctx, id, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.OrderStatus) error); ok {
		r0 = rf(ctx, id, newStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderStatusUpdater_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockOrderStatusUpdater_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - newStatus domain.OrderStatus
func (_e *MockOrderStatusUpdater_Expecter) UpdateOrderStatus(ctx interface{}, id interface{}, newStatus interface{}) *MockOrderStatusUpdater_UpdateOrderStatus_Call {
	return &MockOrderStatusUpdater_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, id, newStatus)}
}

func (_c *MockOrderStatusUpdater_UpdateOrderStatus_Call) Run(run func(ctx context.Context, id string, newStatus domain.OrderStatus)) *MockOrderStatusUpdater_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.OrderStatus))
	})
	return _c
}

func (_c *MockOrderStatusUpdater_UpdateOrderStatus_Call) Return(_a0 error) *MockOrderStatusUpdater_UpdateOrderStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderStatusUpdater_UpdateOrderStatus_Call) RunAndReturn(run func(context.Context, string, domain.OrderStatus) error) *MockOrderStatusUpdater_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderStatusUpdater creates a new instance of MockOrderStatusUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderStatusUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderStatusUpdater {
	mock := &MockOrderStatusUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
