// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockStockDecreaser is an autogenerated mock type for the StockDecreaser type
type MockStockDecreaser struct {
	mock.Mock
}

type MockStockDecreaser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockDecreaser) EXPECT() *MockStockDecreaser_Expecter {
	return &MockStockDecreaser_Expecter{mock: &_m.Mock}
}

// DecreaseStockWithTx provides a mock function with given fields: ctx, tx, restaurantID, menuItemID, quantity
func (_m *MockStockDecreaser) DecreaseStockWithTx(ctx context.Context, tx pgx.Tx, restaurantID string, menuItemID string, quantity int) error {
	ret := _m.Called(ctx, tx, restaurantID, menuItemID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseStockWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string, string, int) error); ok {
		r0 = rf(ctx, tx, restaurantID, menuItemID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockDecreaser_DecreaseStockWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecreaseStockWithTx'
type MockStockDecreaser_DecreaseStockWithTx_Call struct {
	*mock.Call
}

// DecreaseStockWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - restaurantID string
//   - menuItemID string
//   - quantity int
func (_e *MockStockDecreaser_Expecter) DecreaseStockWithTx(ctx interface{}, tx interface{}, restaurantID interface{}, menuItemID interface{}, quantity interface{}) *MockStockDecreaser_DecreaseStockWithTx_Call {
	return &MockStockDecreaser_DecreaseStockWithTx_Call{Call: _e.mock.On("DecreaseStockWithTx", ctx, tx, restaurantID, menuItemID, quantity)}
}

func (_c *MockStockDecreaser_DecreaseStockWithTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, restaurantID string, menuItemID string, quantity int)) *MockStockDecreaser_DecreaseStockWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(string), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockStockDecreaser_DecreaseStockWithTx_Call) Return(_a0 error) *MockStockDecreaser_DecreaseStockWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockDecreaser_DecreaseStockWithTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, string, string, int) error) *MockStockDecreaser_DecreaseStockWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockDecreaser creates a new instance of MockStockDecreaser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockDecreaser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockDecreaser {
	mock := &MockStockDecreaser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
