// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/seWy-bit/GO-and-eat/internal/order/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderGetter is an autogenerated mock type for the OrderGetter type
type MockOrderGetter struct {
	mock.Mock
}

type MockOrderGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderGetter) EXPECT() *MockOrderGetter_Expecter {
	return &MockOrderGetter_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *MockOrderGetter) GetOrder(ctx context.Context, id string) (domain.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderGetter_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderGetter_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrderGetter_Expecter) GetOrder(ctx interface{}, id interface{}) *MockOrderGetter_GetOrder_Call {
	return &MockOrderGetter_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockOrderGetter_GetOrder_Call) Run(run func(ctx context.Context, id string)) *MockOrderGetter_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrderGetter_GetOrder_Call) Return(_a0 domain.Order, _a1 error) *MockOrderGetter_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderGetter_GetOrder_Call) RunAndReturn(run func(context.Context, string) (domain.Order, error)) *MockOrderGetter_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderGetter creates a new instance of MockOrderGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderGetter {
	mock := &MockOrderGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
